/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodos;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/*
* By GatomanJuarez
*/

public class NewtonInte extends javax.swing.JFrame {

    /**
     * Creates new form NewtonInte
     */
    public NewtonInte() {
        initComponents();
        this.setTitle("Interpolacion de Newton By Gatoman");
    }

    double[] arrayX = new double[6];
    double[] arrayD = new double[6];
    double[] arrayResultados = new double[4];
    double x = 0;
    byte contador = 0;

    private double lineal(double x) {
        double resultado = 0;
        resultado = arrayD[0] + (((arrayD[1] - arrayD[0]) / (arrayX[1] - arrayX[0])) * (x - arrayX[0]));
        arrayResultados[0] = resultado;
        return resultado;
    }

    private double cuadratica(double x) {
        double resultado;
        resultado = arrayResultados[0] + (((((arrayD[2] - arrayD[1]) / (arrayX[2] - arrayX[1])) - ((arrayD[1] - arrayD[0]) / (arrayX[1] - arrayX[0]))) / (arrayX[2] - arrayX[0])) * ((x - arrayX[1]) * (x - arrayX[0])));
        arrayResultados[1] = resultado;
        return resultado;
    }

    private double newton4(double x) {
        double resultado, d123, d012, auxiliar1;
        d123 = (((arrayD[3] - arrayD[2]) / (arrayX[3] - arrayX[2])) - ((arrayD[2] - arrayD[1]) / (arrayX[2] - arrayX[1]))) / (arrayX[3] - arrayX[1]);
        d012 = (((arrayD[2] - arrayD[1]) / (arrayX[2] - arrayX[1])) - ((arrayD[1] - arrayD[0]) / (arrayX[1] - arrayX[0]))) / (arrayX[2] - arrayX[0]);
        auxiliar1 = ((x - arrayX[0]) * (x - arrayX[1]) * (x - arrayX[2]));
        resultado = arrayResultados[1] + ((d123 - d012) / (arrayX[3] - arrayX[0])) * auxiliar1;
        arrayResultados[2] = resultado;
        return resultado;
    }

    private double newton5(double x) {
        double resultado, d23, d12, d123, d10, d012, d0123, auxiliar1, auxiliar2;
        d23 = (arrayD[3] - arrayD[2]) / (arrayX[3] - arrayX[2]);
        d12 = (arrayD[2] - arrayD[1]) / (arrayX[2] - arrayX[1]);
        d123 = (d23 - d12) / (arrayX[3] - arrayX[1]);
        d10 = (arrayD[1] - arrayD[0]) / (arrayX[1] - arrayX[0]);
        d012 = (d12 - d10) / (arrayX[2] - arrayX[0]);
        d0123 = (d123 - d012) / (arrayX[3] - arrayX[0]);
        double d234, d34, d1234;
        d34 = (arrayD[4] - arrayD[3]) / (arrayX[4] - arrayX[3]);
        d234 = (d34 - d23) / (arrayX[4] - arrayX[2]);
        d123 = (d23 - d12) / (arrayX[3] - arrayX[1]);
        d1234 = (d234 - d123) / (arrayX[4] - arrayX[1]);
        auxiliar1 = (d1234 - d0123) / (arrayX[4] - arrayX[0]);
        auxiliar2 = (x - arrayX[0]) * (x - arrayX[1]) * (x - arrayX[2]) * (x - arrayX[3]);
        resultado = arrayResultados[2] + (auxiliar1 * auxiliar2);
        arrayResultados[3] = resultado;
        return resultado;
    }

    private double newton6(double x) {
        double auxiliar1, resultado, auxiliarIzquierda, auxiliar2, auxiliar3, auxiliar4, auxiliar5, auxiliar6, auxiliar7, auxiliar8, auxiliar9, auxiliar10;
        auxiliar1 = (arrayD[5] - arrayD[4]) / (arrayX[5] - arrayX[4]);
        auxiliar4 = (arrayD[4] - arrayD[3]) / (arrayX[4] - arrayX[3]);
        auxiliar5 = (auxiliar1 - auxiliar4) / (arrayX[5] - arrayX[3]);
        auxiliar1 = 0;
        auxiliar4 = 0;
        auxiliar1 = (arrayD[4] - arrayD[3]) / (arrayX[4] - arrayX[3]);
        auxiliar4 = (arrayD[3] - arrayD[2]) / (arrayX[3] - arrayX[2]);
        auxiliar6 = (auxiliar1 - auxiliar4) / (arrayX[4] - arrayX[2]);
        auxiliar7 = (auxiliar5 - auxiliar6) / (arrayX[4] - arrayX[2]);

        auxiliar1 = 0;
        auxiliar4 = 0;
        auxiliar1 = (arrayD[4] - arrayD[3]) / (arrayX[4] - arrayX[3]);
        auxiliar4 = (arrayD[3] - arrayD[2]) / (arrayX[3] - arrayX[2]);
        auxiliar8 = (auxiliar1 - auxiliar4) / (arrayX[4] - arrayX[2]);
        auxiliar1 = 0;
        auxiliar4 = 0;
        auxiliar1 = (arrayD[3] - arrayD[2]) / (arrayX[3] - arrayX[2]);
        auxiliar4 = (arrayD[2] - arrayD[1]) / (arrayX[2] - arrayX[1]);
        auxiliar10 = (auxiliar1 - auxiliar4) / (arrayX[3] - arrayX[1]);
        auxiliar9 = (auxiliar8 - auxiliar10) / (arrayX[4] - arrayX[1]);

        auxiliarIzquierda = (auxiliar7 - auxiliar9) / (arrayX[5] - arrayX[1]);
        auxiliar2 = (auxiliarIzquierda - arrayResultados[3]) / (arrayX[5] - arrayX[0]);
        auxiliar3 = (x - arrayX[0]) * (x - arrayX[1]) * (x - arrayX[2]) * (x - arrayX[3]) * (x - arrayX[4]);
        resultado = arrayResultados[3] + (auxiliar2 * auxiliar3);
        return resultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txt14 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt12 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());

        jLabel13.setText("d4");

        jLabel11.setText("d2");

        jLabel12.setText("d3");

        jLabel16.setText("El valor de tu punto es:");

        jLabel9.setText("d0");

        jLabel10.setText("d1");

        jLabel14.setText("X3");

        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });

        jLabel2.setText("En caso de no llenar todas las cajas poner un 0.");

        jButton1.setText("Limpiar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Ingresa los valores de las x y d0,.(Ingresa los X y D que quieras).");

        jButton2.setText("Calcular");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("X2");

        jLabel5.setText("X1");

        jLabel3.setText("Ahora el valor de x:");

        jLabel4.setText("X0");

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("X4");

        jLabel8.setText("X5");

        jLabel15.setText("d5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txt4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txt3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt1))
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt15)
                                    .addComponent(txt5))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton2)
                                .addGap(33, 33, 33)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt12.setText("");
        txt7.setText("");
        txt8.setText("");
        txt9.setText("");
        txt10.setText("");
        txt11.setText("");
        txt12.setText("");
        txt14.setText("");
        txt15.setText("");
        txt16.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            arrayX[0] = Double.parseDouble(txt1.getText());
            arrayX[1] = Double.parseDouble(txt2.getText());
            arrayX[2] = Double.parseDouble(txt3.getText());
            arrayX[3] = Double.parseDouble(txt4.getText());
            arrayX[4] = Double.parseDouble(txt5.getText());
            arrayX[5] = Double.parseDouble(txt15.getText());
            x = Double.parseDouble(txt12.getText());

            arrayD[0] = Double.parseDouble(txt7.getText());
            arrayD[1] = Double.parseDouble(txt8.getText());
            arrayD[2] = Double.parseDouble(txt9.getText());
            arrayD[3] = Double.parseDouble(txt10.getText());
            arrayD[4] = Double.parseDouble(txt11.getText());
            arrayD[5] = Double.parseDouble(txt16.getText());
            contador = 0;
            if (arrayX[0] != 0) {
                contador += 1;
            }
            if (arrayX[1] != 0) {
                contador += 1;
            }
            if (arrayX[2] != 0) {
                contador += 1;
            }
            if (arrayX[3] != 0) {
                contador += 1;
            }
            if (arrayX[4] != 0) {
                contador += 1;
            }

            double auxiliar = 0;

            switch (contador) {
                case 2:
                    auxiliar = lineal(x);
                    txt14.setText(auxiliar + "");
                    break;
                case 3:
                    lineal(x);
                    auxiliar = cuadratica(x);
                    txt14.setText(auxiliar + "");
                    break;

                case 4:
                    lineal(x);
                    cuadratica(x);
                    auxiliar = newton4(x);
                    txt14.setText(auxiliar + "");
                    break;

                case 5:
                    lineal(x);
                    cuadratica(x);
                    newton4(x);
                    auxiliar = newton5(x);
                    txt14.setText(auxiliar + "");
                    break;

                case 6:
                    lineal(x);
                    cuadratica(x);
                    newton4(x);
                    newton5(x);
                    auxiliar = newton6(x);
                    txt14.setText(auxiliar + "");
                    break;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, rellena todas las cajas con valores numericos. " + e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewtonInte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewtonInte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewtonInte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewtonInte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewtonInte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
